# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# run OPA rego linters
- repo: https://github.com/anderseknert/pre-commit-opa
  rev: v1.5.1
  hooks:
  - id: opa-fmt
    args: ['_policy/']
  - id: opa-check
    args: ['_policy/']
  - id: opa-test
    args: ['_policy/']
    #- id: conftest-test
    #- id: conftest-verify
