# config.yml
# netlify CMS configuration
# Docs: https://www.netlifycms.org/docs/jekyll/
---
backend:
  name: github
  repo: momesh/momesh.github.io
  branch: main
media_folder: 'assets/uploads'
collections:
  - name: 'authors'
    label: 'Authors'
    label_singular: 'Author'
    folder: '_authors/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'author' }
      - { label: 'Short Name', name: 'name', widget: 'string' }
      - { label: 'Display Name', name: 'display_name', widget: 'string' }
      - { label: 'Bio', name: 'body', widget: 'hidden' }

  - name: 'status'
    label: 'Status Summary'
    editor:
      preview: true
    files:
      - label: 'Summary'
        name: 'status'
        file: 'status.md'
        fields:
          - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'updates'
    label: 'Status Updates'
    label_singular: 'Update'
    create: true
    editor:
      preview: true
    folder: '_updates/'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: 'name',
        }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'update' }
      - { label: 'Parent', name: 'parent', widget: 'hidden', default: 'Status' }
      - { label: 'Content', name: 'body', widget: 'markdown' }

  - name: 'docs'
    label: 'Documentation'
    label_singular: 'Page'
    create: true
    editor:
      preview: true
    folder: '_docs/'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'docs' }
      - { label: 'Parent', name: 'parent', widget: 'hidden', default: 'Documentation' }
      - { label: 'Tags', name: 'tags', required: false, hint: "router, mesh", widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }


  - name: 'equipment'
    label: 'Equipment'
    label_singular: 'Device'
    create: true
    editor:
      preview: true
    folder: '_equipment/'
    fields:
      - { label: 'Model', name: 'model', widget: 'string', hint: "Omnitik 5AC PoE" }
      - { label: 'Vendor', name: 'vendor', widget: 'string', hint: "Mikrotik" }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'equipment' }
      - { label: 'Summary', name: 'summary', widget: 'string', hint: "short summary of use" }
      - { label: 'MSRP', name: 'msrp', required: false, hint: "$USD", widget: 'number' }
      - { label: 'Protocols', name: 'protocols', required: false, hint: "802.11ac", widget: 'list' }
      - { label: 'Features', name: 'features', required: false, hint: "router, mesh", widget: 'list' }
      - { label: 'Frequencies', name: 'frequencies', required: false, hint: "60GHz",  widget: 'list' }
      - { label: 'Range in Meters', name: 'range_meters', required: false, hint: "400", widget: 'number' }
      - { label: 'Power Requirements', name: 'power_req', required: false, hint: "28v", widget: 'string' }
      - { label: 'Vendor URL', name: 'vendor_url', required: false, hint: "link to vendor site", widget: 'string' }
      - { label: 'Purchase URL', name: 'purchase_url', required: false, hint: "link to baltic networks for purchase", widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }


