# config.yml
# netlify CMS configuration
# Docs: https://www.netlifycms.org/docs/jekyll/
---
backend:
  name: github
  repo: momesh/momesh.github.io
  branch: main
media_folder: 'assets/uploads'
collections:
  - name: 'authors'
    label: 'Authors'
    label_singular: 'Author'
    slug: '{{ name | slugify }}'
    folder: '_authors/'
    create: true
    delete: false
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'author' }
      - { label: 'Short Name', name: 'name', widget: 'string' }
      - { label: 'Display Name', name: 'display_name', widget: 'string' }
      - { label: 'Bio', name: 'body', widget: 'hidden' }

  - name: 'status'
    label: 'Status Summary'
    editor:
      preview: true
    files:
      - label: 'Summary'
        name: 'status'
        file: 'status.md'
        fields:
          - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'updates'
    label: 'Status Updates'
    label_singular: 'Update'
    create: true
    delete: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    folder: '_updates/'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', default: 'Update' }
      - { label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: 'name',
        }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'update' }
      - { label: 'Created', name: 'date', widget: 'datetime' }
      - { label: 'Level', name: 'level', widget: 'select', default: 'info', options: ["info", "minor", "important", "outage"] }
      - { label: 'Outage Start', name: 'outage_begin', widget: 'datetime', required: false, default: '' }
      - { label: 'Outage End', name: 'outage_end', widget: 'datetime', required: false, default: '' }
      - { label: 'Parent', name: 'parent', widget: 'hidden', default: 'Status' }
      - { label: 'Content', name: 'body', widget: 'markdown' }

  - name: 'docs'
    label: 'Documentation'
    label_singular: 'Page'
    slug: '{{ title | slugify }}'
    create: true
    delete: true
    editor:
      preview: true
    folder: '_docs/'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'docs' }
      - { label: 'Parent', name: 'parent', widget: 'hidden', default: 'Documentation' }
      - { label: 'Categories', name: 'categories', widget: 'select', multiple: true, options: ['How To Guides', 'Reference', 'Explanation'], required: false }
      - { label: 'Tags', name: 'tags', required: false, widget: 'select', multiple: true, options: ['network', 'services', 'platform', 'security'] }
      - { label: 'Body', name: 'body', widget: 'markdown' }


  - name: 'equipment'
    label: 'Equipment'
    label_singular: 'Device'
    slug: '{{ vendor | slugify }}-{{ model | slugify }}'
    create: true
    delete: false
    editor:
      preview: true
    folder: '_equipment/'
    fields:
      - { label: 'Model', name: 'model', widget: 'string', hint: "Omnitik 5AC PoE" }
      - { label: 'Vendor', name: 'vendor', widget: 'string', hint: "Mikrotik" }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'equipment' }
      - { label: 'Summary', name: 'summary', widget: 'string', hint: "short summary of use" }
      - { label: 'MSRP', name: 'msrp', required: false, hint: "$USD", widget: 'number' }
      - { label: 'Features', name: 'features', required: false, widget: 'select', multiple: true, options: ['router', 'mesh', 'access point', 'PTP', 'PTMP', 'indoor', 'outdoor', 'sector antenna', 'CPE'] }
      - { label: 'Protocols', name: 'protocols', required: false, widget: 'select', multiple: true, options: ['802.11ac', '802.11ax', 'terragraph'] }
      - { label: 'Frequencies', name: 'frequencies', required: false, widget: 'select', multiple: true, options: ['2.4GHz', '5GHz', '60GHz', '11GHz', '24GHz', '6GHz'] }
      - { label: 'Range in Meters', name: 'range_meters', required: false, hint: "400", widget: 'number' }
      - { label: 'Power Requirements', name: 'power_req', required: false, hint: "28v", widget: 'string' }
      - { label: 'Vendor URL', name: 'vendor_url', required: false, hint: "link to vendor site", widget: 'string' }
      - { label: 'Purchase URL', name: 'purchase_url', required: false, hint: "link to baltic networks for purchase", widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }


