# Run policy enforcement
name: policy-checker

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup OPA binary
      uses: open-policy-agent/setup-opa@v1
      with:
        version: 0.40.x

    - name: Setup Conftest
      uses: princespaghetti/setup-conftest@v1
      with:
        version: 0.30.x

    - name: run conftest against _data/
      run: conftest test -p _policy _data/
